const global = {
  assessor_task: 'assesors_task',
  validators_task: 'validators_task',
  validator_task_ext: 'validator_task_ext',
  assessor_name: 'assessor',
  validator_name: 'validator',
  validation_date: 'validation_date',
  assessor_date: 'assessor_date',
  validation_project: 'validation_project',
  assesor_project: 'assesor_project',
  right_answer_ER1: 'right_answer_ER1',
  right_answer_ER2: 'right_answer_ER2',
  availability_assessor: 'availability_assessor',
  price_assessor: 'price_assessor',
  quality_assesor: 'quality_assesor',
  discrimination_assesor: 'discrimination_assesor',
  availability_validator: 'availability_validator',
  price_validator: 'price_validator',
  quality_validator: 'quality_validator',
  discrimination_validator: 'discrimination_validator',
  comment_by_validator: 'comment_by_validator',
  reason_by_validator_avail: 'reason_by_validator_avail',
  reason_by_validator_discr: 'reason_by_validator_discr',
  reason_by_validator_price: 'reason_by_validator_price',
  doubt: 'doubt',
}

module.exports = global
