name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: [mac, win]

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Fix permissions
      - name: Fix permissions for app-builder and electron-builder
        run: |
          chmod +x ./node_modules/app-builder-bin/mac/app-builder_arm64
          chmod +x ./node_modules/.bin/electron-builder

      # Build and publish Electron app
      - name: Build and Publish Electron app for ${{ matrix.platform }}
        run: |
          if [ "${{ matrix.platform }}" == "mac" ]; then
            npm run electron-builder -- --mac --publish always
          else
            npm run electron-builder -- --win --publish always
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Ensure artifacts are in the release
      - name: Ensure build artifacts exist
        run: ls -l dist/

      # Publish GitHub Release
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.dmg
            dist/*.exe
            dist/latest*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
