name: Build and Release

on:
  push:
    tags:
      - 'v*' # Триггер при пуше тегов, например, v1.0.0

jobs:
  release:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: [mac, win]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Fix permissions for app-builder and electron-builder
        run: |
          chmod +x ./node_modules/app-builder-bin/mac/app-builder_arm64
          chmod +x ./node_modules/.bin/electron-builder

      - name: Build Electron app for ${{ matrix.platform }}
        run: |
          if [ "${{ matrix.platform }}" == "mac" ]; then
            npm run build -- --mac
          else
            npm run build -- --win
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
