name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: [mac, win]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Fix permissions for app-builder and electron-builder
        run: |
          chmod +x ./node_modules/app-builder-bin/mac/app-builder_arm64
          chmod +x ./node_modules/.bin/electron-builder

      - name: Build Electron app for ${{ matrix.platform }}
        run: |
          if [ "${{ matrix.platform }}" == "mac" ]; then
            npm run electron-builder -- --mac
          else
            npm run electron-builder -- --win
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove Gatekeeper quarantine flag (macOS)
        if: matrix.platform == 'mac'
        run: |
          if ls dist/*.app 1> /dev/null 2>&1; then
            sudo xattr -dr com.apple.quarantine dist/*.app
          else
            echo "No .app files found, skipping xattr command."
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download macOS build artifacts
        if: ${{ matrix.platform == 'mac' }}
        uses: actions/download-artifact@v4
        with:
          name: mac-build
          path: dist/mac-build

      - name: Download Windows build artifacts
        if: ${{ matrix.platform == 'win' }}
        uses: actions/download-artifact@v4
        with:
          name: win-build
          path: dist/win-build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/mac-build/*.dmg
            dist/mac-build/*.app
            dist/win-build/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
