name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: [mac, win]

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Fix permissions
      - name: Fix permissions for app-builder and electron-builder
        run: |
          chmod +x ./node_modules/app-builder-bin/mac/app-builder_arm64
          chmod +x ./node_modules/.bin/electron-builder

      # Build the app for the specific platform
      - name: Build Electron app for ${{ matrix.platform }}
        run: |
          if [ "${{ matrix.platform }}" == "mac" ]; then
            npm run electron-builder -- --mac --publish onTagOrDraft
          else
            npm run electron-builder -- --win --publish onTagOrDraft
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Verify build output
      - name: Verify build output
        run: ls -l dist/

      # Upload macOS build artifacts
      - name: Upload macOS build artifacts
        if: matrix.platform == 'mac'
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: |
            dist/*.dmg
            dist/latest-mac.yml

      # Upload Windows build artifacts
      - name: Upload Windows build artifacts
        if: matrix.platform == 'win'
        uses: actions/upload-artifact@v4
        with:
          name: win-build
          path: |
            dist/*.exe
            dist/latest.yml

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Download artifacts
      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: mac-build
          path: ./dist/mac

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: win-build
          path: ./dist/win

        # Create GitHub Release

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
